export const FETCH_ALL_START = 'FETCH_ALL_START';
export const FETCH_ALL_SUCCEED = 'FETCH_ALL_SUCCEED';
export const FETCH_ALL_FAILED = 'FETCH_ALL_FAILED';

export const SAVE_TASK_START = 'SAVE_TASK_START';
export const SAVE_TASK_SUCCEED = 'SAVE_TASK_SUCCEED';
export const SAVE_TASK_FAILED = 'SAVE_TASK_FAILED';

export const COMPLETE_TASK_START = 'COMPLETE_TASK_START';
export const COMPLETE_TASK_SUCCEED = 'COMPLETE_TASK_SUCCEED';
export const COMPLETE_TASK_FAILED = 'COMPLETE_TASK_FAILED';

export const RESET_TASK_START = 'RESET_TASK_START';
export const RESET_TASK_SUCCEED = 'RESET_TASK_SUCCEED';
export const RESET_TASK_FAILED = 'RESET_TASK_FAILED';

export const EDIT_TASK_START = 'EDIT_TASK_START';
export const EDIT_TASK_SUCCEED = 'EDIT_TASK_SUCCEED';
export const EDIT_TASK_FAILED = 'EDIT_TASK_FAILED';

export const DELETE_TASK_START = 'DELETE_TASK_START';
export const DELETE_TASK_SUCCEED = 'DELETE_TASK_SUCCEED';
export const DELETE_TASK_FAILED = 'DELETE_TASK_FAILED';

export const SET_SELECTED_TASK = 'SET_SELECTED_TASK';
